#!/usr/bin/env bash

#=== SH_SCRIPT  ================================================================
#         NAME:   CVBuild
#  DESCRIPTION:   A script to build a Awesome LaTeX CV into a PDF file.
#         DATE:   2022/05/21
#===============================================================================

#-----------------------------------------------------------------------
#  Default values
#-----------------------------------------------------------------------

# e - script stops on error (return !=0)
# u - error if undefined variable
# o pipefail - script fails if one of piped command fails
# x - output each line (debug)
set -euo pipefail

SCRIPT_VERSION="0.1"
SHORT_DESCRIPTION="A script to build a Awesome LaTeX CV into a PDF file."
SCRIPT_NAME="CVBuild"
SCRIPT_RUN="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"


#===  FUNCTION  ================================================================
#         NAME:   Version
#  DESCRIPTION:   Show script name, script version and short description.
#===============================================================================
function version()
{
    echo -e "$SCRIPT_NAME v$SCRIPT_VERSION, ${SHORT_DESCRIPTION,}"

}  # ------------  end of function version  ------------


#===  FUNCTION  ================================================================
#         NAME:   help
#  DESCRIPTION:   Show the script usage and documentation help
#===============================================================================
function help()
{
    echo -e "Usage: $SCRIPT_RUN [OPTION]... [FILE]
       $SCRIPT_RUN [OPTION]... [FILE] [OUTFILE]

Options:
  -h|help          Display this message
  -v|version       Display script version"

}  # ------------  end of function help  ------------


#-------------------------------------------------------------------------------
#  Handle command line arguments
#-------------------------------------------------------------------------------
while getopts ":hv" opt
    do
        case $opt in
            h|help)
                version
                help
                exit 0
                ;;
            v|version)
                version
                exit 0
                ;;
            *)
                echo -e "$SCRIPT_NAME: Invalid option -- '-$OPTARG'"
                help
                exit 1
                ;;
    esac
done    # ----------  end of function usage  ----------
shift $(($OPTIND-1))

