#!/usr/bin/env bash

#=== SH_SCRIPT  ================================================================
#         NAME:   CVBuild
#  DESCRIPTION:   Short description
#         DATE:   2022/05/21
#===============================================================================

#-----------------------------------------------------------------------
#  Default values
#-----------------------------------------------------------------------

# e - script stops on error (return !=0)
# u - error if undefined variable
# o pipefail - script fails if one of piped command fails
# x - output each line (debug)
set -euo pipefail

SCRIPT_VERSION="0.1"
SHORT_DESCRIPTION="Short description"
SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"


#====  FUNCTION  ================================================================
#         NAME:   version
#  DESCRIPTION:   Show script name, script version and short description
#===============================================================================
function version()
{
    echo -e "$SCRIPT_NAME $SCRIPT_VERSION $SHORT_DESCRIPTION"

}  # ------------  end of function version  ------------


#====  FUNCTION  ================================================================
#         NAME:   help
#  DESCRIPTION:   Show the script usage and documentation help
#===============================================================================
function help()
{
    echo -e "Usage: $SCRIPT_NAME [OPTION]... [FILE]
     $SCRIPT_NAME [OPTION]... [FILE] [OUTFILE]

    Options:
    -p|presentation [FILE]  Replace default presentation text with [FILE]
    -h|help                 Display this message
    -v|version    Display script version"

}  # ------------  end of function help  ------------


#-------------------------------------------------------------------------------
#  Handle command line arguments
#-------------------------------------------------------------------------------
while getopts ":hvr:i:o:" opt
    do
        case $opt in
            r|resume)
                ;;
            i|input)
                ;;
            o|output)
                ;;
            h|help)
                version
                help
                exit 0
                ;;
            v|version)
                echo " -- Version $__ScriptVersion"
                exit 0
                ;;
            *)
                echo -e "$SCRIPT_NAME: Invalid option -- '$opt'"
                help
                exit 1
                ;;
    esac
done    # ----------  end of function usage  ----------
shift $(($OPTIND-1))

